CREATE DATABASE ATIVIDADE;
USE ATIVIDADE;

CREATE TABLE LOJAS (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  NOME VARCHAR(100) NOT NULL,
  CNPJ VARCHAR(18) UNIQUE NOT NULL,
  EMAIL VARCHAR(100),
  TELEFONE VARCHAR(20),
  ENDERECO VARCHAR(200),
  SENHA VARCHAR (100),
  CRIADO_EM TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE PRODUTO(
	ID_PRODUTO INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(15) UNIQUE NOT NULL,
    QUANTIDADE INT NOT NULL,
    FORNECEDOR VARCHAR (15) NOT NULL,
    PRECO DECIMAL(10,2) NOT NULL
);

CREATE TABLE FUNCIONARIO(
	ID_FUNCIONARIO INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    SENHA VARCHAR (100) NOT NULL
);


-- Lista todos os Itens da Tabela
SELECT * FROM FUNCIONARIO;

-- Método de busca
SELECT * FROM LOJAS 
WHERE USUARIO LIKE '%João%';

-- Atualizar dados
UPDATE LOJAS 
SET EMAIL = 'novoemail@gmail.com' , TELEFONE = '7188888'
WHERE ID =1;

-- Deletar algum registro
DELETE FROM LOJAS
WHERE ID =2;