CREATE DATABASE ATIVIDADE;
USE ATIVIDADE;

CREATE TABLE LOGIN(
	ID INT AUTO_INCREMENT PRIMARY KEY,
    USUARIO VARCHAR(40) NOT NULL,
    SENHA VARCHAR(12) NOT NULL,
    EMAIL VARCHAR(20) NOT NULL,
    TELEFONE VARCHAR(12) NOT NULL
);

CREATE TABLE PRODUTO(
	ID_PRODUTO INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(15) UNIQUE NOT NULL,
    QUANTIDADE INT NOT NULL,
    FORNECEDOR VARCHAR (15) NOT NULL,
    PRECO DECIMAL(10,2) NOT NULL
);


INSERT INTO LOGIN (USUARIO, EMAIL, TELEFONE, SENHA)
VALUES ('adm', 'joao@email.com', '11999999999', '12345');

-- Lista todos os Itens da Tabela
SELECT * FROM LOGIN;

-- Método de busca
SELECT * FROM LOGIN 
WHERE USUARIO LIKE '%João%';

-- Atualizar dados
UPDATE LOGIN 
SET EMAIL = 'novoemail@gmail.com' , TELEFONE = '7188888'
WHERE ID =1;

-- Deletar algum registro
DELETE FROM LOGIN
WHERE ID =2;
